
apply plugin: 'com.android.library'

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.facebook.android:facebook-android-sdk:17.0.0'

}

task copyDependencies(type: Copy) {
    configurations.implementation.setCanBeResolved(true)
    from configurations.implementation
    into 'dependencies'
}

android {
    namespace 'com.freshplanet.ane.AirFacebook'

    useLibrary  'org.apache.http.legacy'

    compileSdkVersion 35
    buildToolsVersion '35.0.0'

    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 35
    }
}

