platform :ios, '12.0'

target 'AirFacebook' do
  use_frameworks! 
	pod 'FBSDKCoreKit', '17.0.0'
	pod 'FBSDKShareKit', '17.0.0'
	pod 'FBSDKLoginKit', '17.0.0'
	pod 'FBSDKGamingServicesKit', '17.0.0'
end

