platform :ios, '12.0'

target 'AirFacebook' do
  use_frameworks! 
	pod 'FBSDKCoreKit', '16.3.1'
	pod 'FBSDKShareKit', '16.3.1'
	pod 'FBSDKLoginKit', '16.3.1'
	pod 'FBSDKGamingServicesKit', '16.3.1'
end

